//**************************************SOLAR TRACKING PROGRAM*************************************************///
//**************************************WRITTEN BY *************************************************///
//**************************************MICHAEL OLUWADAMILARE VERISSIMO*************************************************///
/**
 *
 * @author VERI
 */
public class Vecalui extends javax.swing.JFrame {

    /**
     * Creates new form Vecalui
     */
    
      public float initCgpa = 0;
      public float initCgpaUnit = 0;
      public float initCgpaPoint = 0;
      public int noOfCourses = 0;
      public int counter = 0;
      public float coursePointSum = 0;
      public float courseUnitSum = 0;
      public float totalCoursePointSum = 0;
      public float totalCourseUnitSum = 0;
      public float newCgpa =0;
      public String display = "WELCOME!!!";
      
        public int gradeConv ( String temp5){
         char temp7 = temp5.charAt(0) ;
          int point = 0;
         switch (temp7){
                 case 'a':
                 point = 5;
                    break;
                 case 'b':
                 point = 4;
                    break;
                 case 'c':
                 point = 3;
                    break;
                 case 'd':
                 point = 2;
                     break;
                         default :
                             
                             break;
                 
         
         }
         return(point);
}
public String Stat (float grade_point){
  //  jLabel1.
        double c_gpa = grade_point;
        String place = "";
        if  (c_gpa>=4.5)
           place = " You are a FIRST CLASS candidate" ;
        else if(c_gpa>=3.5 && c_gpa<4.5)
            place= " You are a SECOND CLASS UPPER candidate" ;
        else if(c_gpa>=2.5 && c_gpa<3.5)
            place = " You are a SECOND CLASS LOWER candidate";
        else if(c_gpa>=1.5 && c_gpa<2.5)
            place = " You are a THIRD CLASS candidate" ;
        else if(c_gpa<1.5)
            place = " You are a PASS candidate";
        return(place);
    }
    public Vecalui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        KnownCgpaTextField = new javax.swing.JTextField();
        KnownCgpaUnitTextField = new javax.swing.JTextField();
        CourseUnit2CalcTextField = new javax.swing.JTextField();
        CourseUnitValueTextField = new javax.swing.JTextField();
        GradeTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jButton3.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 0));
        jButton3.setText("Enter known Cgpa");
        jButton3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 1, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 51))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 38, 38));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 3, true), "VECAL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 1, 18), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(94, 9, 9));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("This App helps you calculate your CGPA");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0)));
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(94, 9, 9));
        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(display);
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0)));
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(94, 9, 9));
        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter value of known CGPA");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0)));
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(94, 9, 9));
        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Enter value of known CGPA units");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0)));
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(94, 9, 9));
        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Enter number of courses to calculate");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0)));
        jLabel5.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(94, 9, 9));
        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Enter value for course unit");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0)));
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(94, 9, 9));
        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Enter value for course grade (a,b,c,d,e,f)");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(255, 255, 0)));
        jLabel7.setOpaque(true);

        KnownCgpaTextField.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        KnownCgpaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KnownCgpaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnownCgpaTextFieldActionPerformed(evt);
            }
        });

        KnownCgpaUnitTextField.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        KnownCgpaUnitTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KnownCgpaUnitTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnownCgpaUnitTextFieldActionPerformed(evt);
            }
        });

        CourseUnit2CalcTextField.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        CourseUnit2CalcTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CourseUnit2CalcTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseUnit2CalcTextFieldActionPerformed(evt);
            }
        });

        CourseUnitValueTextField.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        CourseUnitValueTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        GradeTextField.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        GradeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Enter known Cgpa");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 1, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 51))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("Enter unit &grade");
        jButton2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 1, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 51))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 0, 0));
        jButton4.setText("Restart Calculation");
        jButton4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 1, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 51))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Verissimo Michael");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(KnownCgpaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(KnownCgpaUnitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(CourseUnit2CalcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(CourseUnitValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(GradeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KnownCgpaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KnownCgpaUnitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseUnit2CalcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CourseUnitValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GradeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KnownCgpaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnownCgpaTextFieldActionPerformed
        // TODO add your handling code here:
         String temp1 = KnownCgpaTextField.getText();
                initCgpa = Float.valueOf(temp1);
                jLabel1.setText("value of known CGPA recieved : " + temp1 );
                jLabel2.setText("Enter the value of known Cgpa unit");
                noOfCourses = 0;
      counter = 0;
       coursePointSum = 0;
      courseUnitSum = 0;
       totalCoursePointSum = 0;
       totalCourseUnitSum = 0;
       newCgpa =0;
    }//GEN-LAST:event_KnownCgpaTextFieldActionPerformed

    private void KnownCgpaUnitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnownCgpaUnitTextFieldActionPerformed
  String temp1 = KnownCgpaUnitTextField.getText();
                initCgpaUnit = Float.valueOf(temp1);
                jLabel1.setText("value of known CGPA Unit recieved : " + temp1 );
                jLabel2.setText("Enter number of courses you want to calculate");  
                 initCgpaPoint = initCgpa*initCgpaUnit;
                 counter = 0;
       coursePointSum = 0;
      courseUnitSum = 0;
       totalCoursePointSum = 0;
       totalCourseUnitSum = 0;
       newCgpa =0;// TODO add your handling code here:
    }//GEN-LAST:event_KnownCgpaUnitTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String temp1 = KnownCgpaTextField.getText();
                initCgpa = Float.valueOf(temp1);
                 temp1 = KnownCgpaUnitTextField.getText();
                initCgpaUnit = Float.valueOf(temp1);
                 jLabel1.setText("known CGPA & CGPA Unit recieved : " + initCgpa + " " + initCgpaUnit );
                jLabel2.setText("Enter number of courses you want to calculate");
                initCgpaPoint = initCgpa*initCgpaUnit;
                 counter = 0;
       coursePointSum = 0;
      courseUnitSum = 0;
       totalCoursePointSum = 0;
       totalCourseUnitSum = 0;
       newCgpa =0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CourseUnit2CalcTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseUnit2CalcTextFieldActionPerformed
        // TODO add your handling code here:
         String temp3 = CourseUnit2CalcTextField.getText();
        
                noOfCourses = Integer.valueOf(temp3);
                 jLabel1.setText("remaining course details to enter " + noOfCourses );
                jLabel2.setText("Enter value for course 1 unit  ");
                counter++;
                jLabel6.setText("Enter value for course " + counter + " unit"  );
                jLabel7.setText("Enter value for course " + counter + " unit grade (a,b,c,d,e,f)"  );
                String temp12 = Integer.toString(noOfCourses);
                    jLabel5.setText("number of course details remaining " );
                    CourseUnit2CalcTextField.setText(temp12);
    }//GEN-LAST:event_CourseUnit2CalcTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         counter++;
        String temp1 = GradeTextField.getText();
                        float temp3 = gradeConv(temp1);
               String temp6 = CourseUnitValueTextField.getText();
                float temp4 = Float.valueOf(temp6);
                temp3 = temp3 * temp4;
                coursePointSum += temp3;
                courseUnitSum += temp4;
                if (counter > noOfCourses){
                totalCoursePointSum = coursePointSum + initCgpaPoint;
                totalCourseUnitSum =  courseUnitSum + initCgpaUnit;
                 newCgpa =  totalCoursePointSum / totalCourseUnitSum;
                  GradeTextField.setText("");
                    CourseUnitValueTextField.setText("");
                 String standing = Stat(newCgpa);
                 jLabel1.setText("Your CGPA is : "  + newCgpa );
                jLabel2.setText(standing);
                String temp12 = Integer.toString(noOfCourses);
                jLabel5.setText("number of course details calculated " );
                    CourseUnit2CalcTextField.setText(temp12);
                }
                else
                {
                    int temp10 = counter -1;
                    int temp11 = noOfCourses - temp10;
                    String temp12 = Integer.toString(temp11);
                    jLabel5.setText("number of course details remaining " );
                    CourseUnit2CalcTextField.setText(temp12);
                    CourseUnitValueTextField.setText("");
                     GradeTextField.setText("");
                     jLabel1.setText("course " + temp10 +" details recieved ");
                jLabel2.setText("Enter details for course " + counter + " of " + noOfCourses);
                 jLabel6.setText("Enter value for course " + counter + " unit"  );
                jLabel7.setText("Enter value for course " + counter + " unit grade (A,B,C,D,E,F)"  );
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here
         jLabel1.setText("This App helps you calculate your CGPA " );
         jLabel2.setText(display);
                jLabel6.setText("Enter value for course unit");
                jLabel7.setText("Enter value for course grade (a,b,c,d,e,f)");
                KnownCgpaTextField.setText("");
                    KnownCgpaUnitTextField.setText("");
                    CourseUnit2CalcTextField.setText("");
                    CourseUnitValueTextField.setText("");
                GradeTextField.setText("");
                   noOfCourses = 0;
      counter = 0;
       coursePointSum = 0;
      courseUnitSum = 0;
       totalCoursePointSum = 0;
       totalCourseUnitSum = 0;
       newCgpa =0;
         initCgpa = 0;
       initCgpaUnit = 0;
        initCgpaPoint = 0;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vecalui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vecalui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vecalui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vecalui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vecalui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CourseUnit2CalcTextField;
    private javax.swing.JTextField CourseUnitValueTextField;
    private javax.swing.JTextField GradeTextField;
    private javax.swing.JTextField KnownCgpaTextField;
    private javax.swing.JTextField KnownCgpaUnitTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
